"""PDF report generation for PCAT analysis results."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Any, Optional

import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

from pcat_workstation.app.config import FAI_HU_MIN, FAI_HU_MAX, FAI_RISK_THRESHOLD


def generate_report(
    output_path: Path,
    patient_id: str,
    study_date: str,
    vessel_stats: Dict[str, Dict[str, Any]],
    cpr_images: Optional[Dict[str, np.ndarray]] = None,
    hu_data: Optional[Dict[str, np.ndarray]] = None,
) -> None:
    """Generate a multi-page PDF report.

    Pages:
    1. Summary page -- patient info + per-vessel FAI table
    2-N. Per-vessel pages -- CPR image (if available) + HU histogram + stats
    """
    with PdfPages(str(output_path)) as pdf:
        # Page 1: Summary
        _draw_summary_page(pdf, patient_id, study_date, vessel_stats)

        # Per-vessel pages
        for vessel, stats in vessel_stats.items():
            if vessel.startswith("_"):  # skip internal keys
                continue
            cpr = cpr_images.get(vessel) if cpr_images else None
            hu = hu_data.get(vessel) if hu_data else None
            _draw_vessel_page(pdf, vessel, stats, cpr, hu)


def _draw_summary_page(pdf, patient_id, study_date, vessel_stats):
    fig = Figure(figsize=(8.5, 11))
    ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])
    ax.axis("off")

    # Title
    ax.text(
        0.5, 0.95, "PCAT Analysis Report",
        fontsize=20, ha="center", va="top", fontweight="bold",
    )
    ax.text(
        0.5, 0.90, f"Patient: {patient_id}   Date: {study_date}",
        fontsize=12, ha="center", va="top",
    )

    # Summary table
    y = 0.80
    ax.text(0.15, y, "Vessel", fontsize=12, fontweight="bold")
    ax.text(0.35, y, "Mean FAI (HU)", fontsize=12, fontweight="bold")
    ax.text(0.55, y, "Fat Fraction", fontsize=12, fontweight="bold")
    ax.text(0.75, y, "Risk", fontsize=12, fontweight="bold")
    y -= 0.03
    ax.axhline(y=y, xmin=0.1, xmax=0.9, color="black", linewidth=0.5)

    for vessel, stats in vessel_stats.items():
        if vessel.startswith("_"):
            continue
        y -= 0.05
        risk = stats.get("fai_risk", "LOW")
        color = "red" if risk == "HIGH" else "green"
        ax.text(0.15, y, vessel, fontsize=11)
        ax.text(0.35, y, f"{stats.get('hu_mean', 0.0):.1f}", fontsize=11)
        ax.text(
            0.55, y, f"{stats.get('fat_fraction', 0.0) * 100:.1f}%", fontsize=11,
        )
        ax.text(0.75, y, risk, fontsize=11, color=color, fontweight="bold")

    # Footer
    ax.text(
        0.5, 0.02,
        "Generated by PCAT Workstation \u2014 Molloi Lab, UC Irvine",
        fontsize=8, ha="center", color="gray",
    )

    pdf.savefig(fig)
    plt.close(fig)


def _draw_vessel_page(pdf, vessel, stats, cpr_image, hu_values):
    fig = Figure(figsize=(8.5, 11))

    # Title
    ax_title = fig.add_axes([0.1, 0.92, 0.8, 0.06])
    ax_title.axis("off")
    ax_title.text(
        0.5, 0.5, f"{vessel} \u2014 Detailed Analysis",
        fontsize=16, ha="center", fontweight="bold",
    )

    # CPR image (top half)
    if cpr_image is not None:
        ax_cpr = fig.add_axes([0.1, 0.50, 0.8, 0.40])
        # Apply vascular window/level (W=800, L=200)
        low = 200.0 - 800.0 / 2.0  # -200
        high = 200.0 + 800.0 / 2.0  # 600
        wl_img = np.clip((cpr_image - low) / (high - low), 0, 1)
        ax_cpr.imshow(wl_img, cmap="gray", aspect="auto")
        ax_cpr.set_title(f"{vessel} CPR", fontsize=12)
        ax_cpr.set_xlabel("Lateral (pixels)")
        ax_cpr.set_ylabel("Arc-length (pixels)")

    # HU histogram (bottom left)
    ax_hist = fig.add_axes([0.1, 0.08, 0.35, 0.35])
    if hu_values is not None and len(hu_values) > 0:
        fat_mask = (hu_values >= FAI_HU_MIN) & (hu_values <= FAI_HU_MAX)
        fat_hu = hu_values[fat_mask]
        if len(fat_hu) > 0:
            ax_hist.hist(
                fat_hu, bins=40, range=(FAI_HU_MIN, FAI_HU_MAX),
                color="#4A90D9", alpha=0.8,
            )
        ax_hist.axvline(
            FAI_RISK_THRESHOLD, linestyle="--", color="red", linewidth=1,
            label=f"{FAI_RISK_THRESHOLD} HU",
        )
        ax_hist.legend(fontsize=8)
    ax_hist.set_xlabel("HU")
    ax_hist.set_ylabel("Count")
    ax_hist.set_title("HU Distribution (FAI range)")

    # Stats box (bottom right)
    ax_stats = fig.add_axes([0.55, 0.08, 0.35, 0.35])
    ax_stats.axis("off")
    text_lines = [
        f"Mean HU: {stats.get('hu_mean', 0.0):.1f}",
        f"Std HU: {stats.get('hu_std', 0.0):.1f}",
        f"Fat fraction: {stats.get('fat_fraction', 0.0) * 100:.1f}%",
        f"VOI voxels: {stats.get('voi_voxels', 0):,}",
        f"Fat voxels: {stats.get('fat_voxels', 0):,}",
        f"Risk: {stats.get('fai_risk', 'LOW')}",
    ]
    for i, line in enumerate(text_lines):
        ax_stats.text(
            0.1, 0.85 - i * 0.14, line,
            fontsize=11, transform=ax_stats.transAxes,
        )
    ax_stats.set_title("Statistics")

    pdf.savefig(fig)
    plt.close(fig)
